
package qlbn;

import Connection.SqlConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tien Nguyen
 */
public class ChiTietBenhNhan extends javax.swing.JFrame {

    Statement statement;
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    public SqlConnection sqlConn = new SqlConnection();

    public ChiTietBenhNhan() {
        initComponents();
        ChiTiet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtThoiGianDT = new javax.swing.JTextField();
        txtThoiGianCC = new javax.swing.JTextField();
        txtThoiGianTC = new javax.swing.JTextField();
        txtSoKiDT = new javax.swing.JTextField();
        txtLoaiBN = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        txtTenBN = new javax.swing.JTextField();
        txtMaBN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtThoiGianDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtThoiGianDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 265, 152, -1));

        txtThoiGianCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtThoiGianCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 152, -1));

        txtThoiGianTC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtThoiGianTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 302, 78, -1));

        txtSoKiDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtSoKiDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 224, 78, -1));

        txtLoaiBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtLoaiBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 183, 78, -1));

        txtGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 78, -1));

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 291, -1));

        txtTuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtTuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 139, 78, -1));

        txtTenBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtTenBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 291, -1));

        txtMaBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtMaBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 98, 76, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Thời gian củng cố");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Thời gian điều trị");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 268, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Thời gian tấn công");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 305, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cân nặng");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 227, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Loại bệnh nhân");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 186, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Địa chỉ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tuổi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 142, 47, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên bệnh nhân");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã bệnh nhân");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 101, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconBack.png"))); // NOI18N
        btnBack.setText("Trở Về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/i5.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 40));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconSave.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/gdthem.jpg"))); // NOI18N
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void ChiTiet() {
        txtMaBN.setEditable(false);
        txtTenBN.setEditable(false);
        txtTuoi.setEditable(false);
        txtGioiTinh.setEditable(false);
        txtLoaiBN.setEditable(false);
        txtDiaChi.setEditable(false);
        txtSoKiDT.setEditable(false);
        // dtpNgayBDDT.setEditable(false);
        txtThoiGianDT.setEditable(false);
        txtThoiGianCC.setEditable(false);
        txtThoiGianTC.setEditable(false);
    }

    public void Sua() {
        txtTenBN.setEditable(true);
        txtTuoi.setEditable(true);
        //txtLoaiBN.setEditable(true);
        txtDiaChi.setEditable(true);
        //txtSoKiDT.setEditable(true);
        //txtThoiGianDT.setEditable(true);
        txtThoiGianCC.setEditable(true);
        txtThoiGianTC.setEditable(true);
    }


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        TimXoaSua tsx = null;
        try {
            tsx = new TimXoaSua();
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChiTietBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        tsx.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        Sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            int maBN = Integer.parseInt(txtMaBN.getText());
            String ten = txtTenBN.getText();
            int tuoi = Integer.parseInt(txtTuoi.getText());
            //String loai = txtTenBN.getText();
            String dc = txtDiaChi.getText();
            int cn = Integer.parseInt(txtSoKiDT.getText());
            int tgdt = Integer.parseInt(txtThoiGianDT.getText());
            int tgcc = Integer.parseInt(txtThoiGianCC.getText());
            int tgtc = Integer.parseInt(txtThoiGianTC.getText());

            conn = sqlConn.getSQLServerConnection();
            ps = conn.prepareStatement("Update BENHNHAN set TENBN=?,TUOI=?,DIACHI=?  where MABN=?");
            ps.setString(1, ten);
            ps.setInt(2, tuoi);
            ps.setString(3, dc);
            ps.setInt(4, maBN);

            int row = ps.executeUpdate();
            if(row > 0){
                JOptionPane.showMessageDialog(null, "cập nhật thành công!");
                try{
                TimXoaSua txs = new TimXoaSua();
                txs.setVisible(true);
                this.setVisible(false);
                }catch(Exception e){
                     JOptionPane.showMessageDialog(null, e);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietBenhNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField txtDiaChi;
    public javax.swing.JTextField txtGioiTinh;
    public javax.swing.JTextField txtLoaiBN;
    public javax.swing.JTextField txtMaBN;
    public javax.swing.JTextField txtSoKiDT;
    public javax.swing.JTextField txtTenBN;
    public javax.swing.JTextField txtThoiGianCC;
    public javax.swing.JTextField txtThoiGianDT;
    public javax.swing.JTextField txtThoiGianTC;
    public javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
