/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbn;

/**
 *
 * @author Tien Nguyen
 */
public class GiaoDienThongTinVePhanMem extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienThongTinVePhanMem
     */
    public GiaoDienThongTinVePhanMem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label11 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label3 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        label4.setText("4 thành viên lớp 17DTHC6-D1");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 20));
        label4.getAccessibleContext().setAccessibleName("4 thành viên lớp 17DTHC6-D1");

        label5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label5.setText("1. Nguyễn Ngọc Thuỷ Tiên");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        label6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label6.setText("2. Nguyễn Hữu Tính");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        label7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label7.setText("3. Đoàn Thanh Lam");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        label9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label9.setText("4. Nguyễn Hữu Đạt");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        label11.setName(""); // NOI18N
        label11.setText("-----------------------------");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        label13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        label13.setText("Liên hệ: ");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        label14.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        label14.setText("Khoa Công Nghệ Thông Tin");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, -1));

        label15.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        label15.setText("Trường Đại Học Công Nghệ Tp.HCM (Hutech)");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 260, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Phát triển bởi");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 30));

        label16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label16.setText("Email: nguyenngocthuytien0607@gmail.com");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 260, -1));
        label16.getAccessibleContext().setAccessibleName("nguyenngocthuytien0607@gmail.com");

        label17.setText("--------------------------------");
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 150, -1));

        label18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label18.setText("SĐT: 0796824757");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PHẦN MỀM QUẢN LÝ BỆNH NHÂN LAO ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Năm phát hành: V2-05/06/2020");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/gd_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconBack.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 110, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        this.setVisible(false);
//        Main_1 frm = new Main_1();
//        frm .setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
//        Main_1 frm = new Main_1();
//        frm .setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongTinVePhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongTinVePhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongTinVePhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongTinVePhanMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienThongTinVePhanMem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label11;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
<<<<<<< HEAD
    private java.awt.Label label8;
=======
    private java.awt.Label label9;
>>>>>>> 109eba274c53215a502a08bbbdc23b06c14e2cd2
    // End of variables declaration//GEN-END:variables
}
