/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbn;

/**
 *
 * @author Tien Nguyen
 */
public class ManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form Main_1
     */
    public ManHinhChinh() {
        initComponents();
        setLocationRelativeTo(null);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemThongTinBenhNhanLao = new javax.swing.JButton();
        btnTimKiemThongTin = new javax.swing.JButton();
        btnThongTinSanPham = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThemThongTinBenhNhanLao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemThongTinBenhNhanLao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconthem.png"))); // NOI18N
        btnThemThongTinBenhNhanLao.setText("QUẢN LÝ LOẠI BỆNH NHÂN");
        btnThemThongTinBenhNhanLao.setAlignmentX(5.0F);
        btnThemThongTinBenhNhanLao.setAlignmentY(5.0F);
        btnThemThongTinBenhNhanLao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThongTinBenhNhanLaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemThongTinBenhNhanLao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 280, 110));

        btnTimKiemThongTin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTimKiemThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/icontimxoasua.png"))); // NOI18N
        btnTimKiemThongTin.setText("QUẢN LÝ THÔNG TIN BỆNH NHÂN");
        btnTimKiemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemThongTinActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiemThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 290, 110));

        btnThongTinSanPham.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThongTinSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconquestion.png"))); // NOI18N
        btnThongTinSanPham.setText("LIÊN HỆ");
        btnThongTinSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinSanPhamActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongTinSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 280, 110));

        btnXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/drug.png"))); // NOI18N
        btnXuatExcel.setText("QUẢN LÝ LOẠI THUỐC");
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 290, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ BỆNH NHÂN LAO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 480, 40));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/hinhnen_main.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemThongTinBenhNhanLaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThongTinBenhNhanLaoActionPerformed
        // TODO add your handling code here:
        ThemLoaiBenhNhan themLoaiBN = new ThemLoaiBenhNhan();
        this.setVisible(false);
        themLoaiBN.setVisible(true);
    }//GEN-LAST:event_btnThemThongTinBenhNhanLaoActionPerformed

    private void btnTimKiemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemThongTinActionPerformed
        // TODO add your handling code here:
        TimXoaSua frm = new TimXoaSua();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTimKiemThongTinActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        ThemLoaiThuoc tlt = new ThemLoaiThuoc();
        this.setVisible(false);
        tlt.setVisible(true);
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnThongTinSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinSanPhamActionPerformed
        // TODO add your handling code here:
        GiaoDienThongTinVePhanMem a = new GiaoDienThongTinVePhanMem();
        a.setVisible(true);
        
    }//GEN-LAST:event_btnThongTinSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManHinhChinh().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemThongTinBenhNhanLao;
    private javax.swing.JButton btnThongTinSanPham;
    private javax.swing.JButton btnTimKiemThongTin;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
